/*
 * @Description:
 * @Autor: wxp
 * @Date: 2022-10-09 15:37:08
 */
import {useFocusEffect} from '@react-navigation/native';
import React, {useCallback, useRef, useState} from 'react';
import {View, Text, StyleSheet, ScrollView, TouchableOpacity, ActivityIndicator} from 'react-native';
import FastImage from 'react-native-fast-image';
import ScrollableTabView from 'react-native-scrollable-tab-view';
import {useJump} from '~/components/hooks';
import {AlbumCard} from '~/components/Product';
import {isIphoneX, px} from '~/utils/appUtil';
import ScrollableTabBar from '../components/ScrollableTabBar';
import {getData, getList} from './services';

const SubjectCollection = ({navigation, route}) => {
    const jump = useJump();
    const [data, setData] = useState();
    const [listData, setListData] = useState();
    const tabRef = useRef();

    useFocusEffect(
        useCallback(() => {
            getData().then((res) => {
                if (res.code === '000000') {
                    setData(res.result);
                    let tab = route?.params?.tab || tabRef?.current?.state?.currentPage || 0;
                    setTimeout(() => {
                        tabRef?.current?.goToPage(tab);
                    });
                }
            });
        }, [route?.params?.tab])
    );

    useFocusEffect(
        useCallback(() => {
            let listener = navigation.addListener('beforeRemove', (e) => {
                e.preventDefault();
                navigation.navigate('CreatorCenter');
            });
            return () => listener?.();
        }, [])
    );

    const getListData = (type) => {
        getList({type}).then((res) => {
            if (res.code === '000000') {
                setListData(res.result);
            }
        });
    };

    const onChangeTab = useCallback(
        ({i}) => {
            getListData(data?.header?.[i]?.type);
        },
        [data]
    );

    return data ? (
        <View style={styles.container}>
            <ScrollableTabView
                locked={true}
                ref={tabRef}
                renderTabBar={() => (
                    <ScrollableTabBar
                        style={{paddingHorizontal: px(34), backgroundColor: '#fff', paddingTop: px(10)}}
                    />
                )}
                onChangeTab={onChangeTab}>
                {data?.header?.map?.((item, idx) => (
                    <ScrollView tabLabel={item?.val} key={idx} showsHorizontalScrollIndicator={false} style={{flex: 1}}>
                        <>
                            {listData?.items?.[0] ? (
                                <View style={styles.cardsWrap}>
                                    {listData?.items?.map?.((subject, index) => (
                                        <View style={styles.cardItem} key={index}>
                                            <AlbumCard {...subject} />
                                        </View>
                                    ))}
                                </View>
                            ) : (
                                <View
                                    style={{
                                        backgroundColor: '#fff',
                                        margin: px(16),
                                        marginBottom: 0,
                                        borderRadius: px(6),
                                        paddingVertical: px(60),
                                        alignItems: 'center',
                                    }}>
                                    <FastImage
                                        style={{width: px(120), height: px(64)}}
                                        source={require('~/assets/img/emptyTip/empty.png')}
                                    />
                                    <Text
                                        style={{
                                            fontSize: px(13),
                                            lineHeight: px(18),
                                            color: '#121D3A',
                                            textAlign: 'center',
                                        }}>
                                        暂无内容
                                    </Text>
                                </View>
                            )}
                            {listData?.tip ? <Text style={styles.hint}>{listData?.tip}</Text> : null}
                        </>
                        <View style={{height: 50}} />
                    </ScrollView>
                ))}
            </ScrollableTabView>
            {listData?.button ? (
                <View style={styles.bottomWrap}>
                    <TouchableOpacity
                        activeOpacity={0.7}
                        style={styles.bottomBtn}
                        onPress={() => {
                            jump(listData?.button?.url);
                        }}>
                        <Text style={styles.bottomBtnText}>{listData?.button?.text}</Text>
                    </TouchableOpacity>
                </View>
            ) : null}
        </View>
    ) : null;
};

export default SubjectCollection;

const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    cardsWrap: {
        paddingHorizontal: px(16),
    },
    cardItem: {
        marginTop: px(16),
    },
    hint: {
        fontSize: px(11),
        lineHeight: px(15),
        color: '#9aa0b1',
        marginHorizontal: px(16),
        marginTop: px(12),
    },
    bottomWrap: {
        backgroundColor: '#fff',
        paddingHorizontal: px(16),
        paddingTop: px(8),
        paddingBottom: isIphoneX() ? 34 : px(8),
    },
    bottomBtn: {
        backgroundColor: '#0051cc',
        borderRadius: px(6),
        paddingVertical: px(12),
    },
    bottomBtnText: {
        fontSize: px(15),
        lineHeight: px(21),
        color: '#fff',
        textAlign: 'center',
    },
});
const subjects = [
    {
        subject_id: 101,
        header: {
            title: '安稳入门',
            title_desc: '',
            desc:
                '稳健理财占比资产配置的30%-50%比较合理，多为近期不用但后期需要的长期投资。本专题精选涨跌幅排名前25%的优质债基；适合追求低波动，追求稳稳幸福的投资者\n',
            desc_icon: 'https://static.licaimofang.com/wp-content/uploads/2022/09/yh@3x.png',
            icon: '',
            bg_img: 'https://static.licaimofang.com/wp-content/uploads/2022/09/51664352728_.pic_.png',
            bg_linear: true,
            url: {
                path: 'SpecialDetail',
                type: 1,
                params: {
                    link: 'http://koudai-evolution-h5.yitao.mofanglicai.com.cn/specialDetail',
                    params: {
                        subject_id: 101,
                    },
                },
            },
        },
        img: '',
        img_url: '',
        items: [
            {
                ui_style: 'default',
                id: 57,
                product_id: '003547',
                name: '鹏华丰禄',
                tags: ['中低风险'],
                profit: '<span style="color:#E74949">6.01%</span>',
                profit_desc: '近一年收益率',
                reason_icon: 'https://static.licaimofang.com/wp-content/uploads/2022/09/gray_yh@3x.png',
                chart: [
                    {
                        type: '鹏华丰禄',
                        value: 0,
                        date: '2021-09-30',
                        line: '',
                        area: '',
                    },
                    {
                        type: '鹏华丰禄',
                        value: 0.0011,
                        date: '2021-10-18',
                        line: '',
                        area: '',
                    },
                    {
                        type: '鹏华丰禄',
                        value: 0.0037,
                        date: '2021-10-28',
                        line: '',
                        area: '',
                    },
                    {
                        type: '鹏华丰禄',
                        value: 0.0085,
                        date: '2021-11-08',
                        line: '',
                        area: '',
                    },
                    {
                        type: '鹏华丰禄',
                        value: 0.0104,
                        date: '2021-11-19',
                        line: '',
                        area: '',
                    },
                    {
                        type: '鹏华丰禄',
                        value: 0.0121,
                        date: '2021-12-01',
                        line: '',
                        area: '',
                    },
                    {
                        type: '鹏华丰禄',
                        value: 0.0135,
                        date: '2021-12-13',
                        line: '',
                        area: '',
                    },
                    {
                        type: '鹏华丰禄',
                        value: 0.0149,
                        date: '2021-12-27',
                        line: '',
                        area: '',
                    },
                    {
                        type: '鹏华丰禄',
                        value: 0.017,
                        date: '2022-01-06',
                        line: '',
                        area: '',
                    },
                    {
                        type: '鹏华丰禄',
                        value: 0.0193,
                        date: '2022-01-17',
                        line: '',
                        area: '',
                    },
                    {
                        type: '鹏华丰禄',
                        value: 0.0237,
                        date: '2022-01-26',
                        line: '',
                        area: '',
                    },
                    {
                        type: '鹏华丰禄',
                        value: 0.0259,
                        date: '2022-02-14',
                        line: '',
                        area: '',
                    },
                    {
                        type: '鹏华丰禄',
                        value: 0.0267,
                        date: '2022-02-25',
                        line: '',
                        area: '',
                    },
                    {
                        type: '鹏华丰禄',
                        value: 0.0258,
                        date: '2022-03-10',
                        line: '',
                        area: '',
                    },
                    {
                        type: '鹏华丰禄',
                        value: 0.0282,
                        date: '2022-03-24',
                        line: '',
                        area: '',
                    },
                    {
                        type: '鹏华丰禄',
                        value: 0.0313,
                        date: '2022-04-06',
                        line: '',
                        area: '',
                    },
                    {
                        type: '鹏华丰禄',
                        value: 0.0348,
                        date: '2022-04-15',
                        line: '',
                        area: '',
                    },
                    {
                        type: '鹏华丰禄',
                        value: 0.0368,
                        date: '2022-04-27',
                        line: '',
                        area: '',
                    },
                    {
                        type: '鹏华丰禄',
                        value: 0.0392,
                        date: '2022-05-11',
                        line: '',
                        area: '',
                    },
                    {
                        type: '鹏华丰禄',
                        value: 0.0419,
                        date: '2022-05-20',
                        line: '',
                        area: '',
                    },
                    {
                        type: '鹏华丰禄',
                        value: 0.0436,
                        date: '2022-05-31',
                        line: '',
                        area: '',
                    },
                    {
                        type: '鹏华丰禄',
                        value: 0.0435,
                        date: '2022-06-10',
                        line: '',
                        area: '',
                    },
                    {
                        type: '鹏华丰禄',
                        value: 0.045,
                        date: '2022-06-21',
                        line: '',
                        area: '',
                    },
                    {
                        type: '鹏华丰禄',
                        value: 0.0462,
                        date: '2022-07-01',
                        line: '',
                        area: '',
                    },
                    {
                        type: '鹏华丰禄',
                        value: 0.0484,
                        date: '2022-07-13',
                        line: '',
                        area: '',
                    },
                    {
                        type: '鹏华丰禄',
                        value: 0.0509,
                        date: '2022-07-22',
                        line: '',
                        area: '',
                    },
                    {
                        type: '鹏华丰禄',
                        value: 0.0544,
                        date: '2022-08-02',
                        line: '',
                        area: '',
                    },
                    {
                        type: '鹏华丰禄',
                        value: 0.0555,
                        date: '2022-08-11',
                        line: '',
                        area: '',
                    },
                    {
                        type: '鹏华丰禄',
                        value: 0.0588,
                        date: '2022-08-23',
                        line: '',
                        area: '',
                    },
                    {
                        type: '鹏华丰禄',
                        value: 0.0587,
                        date: '2022-09-01',
                        line: '',
                        area: '',
                    },
                    {
                        type: '鹏华丰禄',
                        value: 0.0604,
                        date: '2022-09-15',
                        line: '',
                        area: '',
                    },
                    {
                        type: '鹏华丰禄',
                        value: 0.0602,
                        date: '2022-09-28',
                        line: '',
                        area: '',
                    },
                ],
                style_type: 1,
                url: {
                    path: 'FundDetail',
                    type: 1,
                    params: {
                        code: '003547',
                    },
                },
            },
            {
                ui_style: 'default',
                id: 58,
                product_id: '004136',
                name: '博时民泽纯债债券',
                tags: ['低风险'],
                profit: '<span style="color:#E74949">3.90%</span>',
                profit_desc: '近一年收益率',
                reason_icon: 'https://static.licaimofang.com/wp-content/uploads/2022/09/gray_yh@3x.png',
                chart: [
                    {
                        type: '博时民泽纯债债券',
                        value: 0,
                        date: '2021-09-28',
                        line: '',
                        area: '',
                    },
                    {
                        type: '博时民泽纯债债券',
                        value: 0.0118,
                        date: '2021-10-18',
                        line: '',
                        area: '',
                    },
                    {
                        type: '博时民泽纯债债券',
                        value: 0.0128,
                        date: '2021-11-01',
                        line: '',
                        area: '',
                    },
                    {
                        type: '博时民泽纯债债券',
                        value: 0.014,
                        date: '2021-11-19',
                        line: '',
                        area: '',
                    },
                    {
                        type: '博时民泽纯债债券',
                        value: 0.0145,
                        date: '2021-12-01',
                        line: '',
                        area: '',
                    },
                    {
                        type: '博时民泽纯债债券',
                        value: 0.0119,
                        date: '2021-12-17',
                        line: '',
                        area: '',
                    },
                    {
                        type: '博时民泽纯债债券',
                        value: 0.0131,
                        date: '2021-12-31',
                        line: '',
                        area: '',
                    },
                    {
                        type: '博时民泽纯债债券',
                        value: 0.014,
                        date: '2022-01-14',
                        line: '',
                        area: '',
                    },
                    {
                        type: '博时民泽纯债债券',
                        value: 0.0158,
                        date: '2022-01-27',
                        line: '',
                        area: '',
                    },
                    {
                        type: '博时民泽纯债债券',
                        value: 0.0165,
                        date: '2022-02-14',
                        line: '',
                        area: '',
                    },
                    {
                        type: '博时民泽纯债债券',
                        value: 0.0159,
                        date: '2022-02-23',
                        line: '',
                        area: '',
                    },
                    {
                        type: '博时民泽纯债债券',
                        value: 0.0143,
                        date: '2022-03-04',
                        line: '',
                        area: '',
                    },
                    {
                        type: '博时民泽纯债债券',
                        value: 0.0146,
                        date: '2022-03-15',
                        line: '',
                        area: '',
                    },
                    {
                        type: '博时民泽纯债债券',
                        value: 0.0144,
                        date: '2022-03-25',
                        line: '',
                        area: '',
                    },
                    {
                        type: '博时民泽纯债债券',
                        value: 0.0264,
                        date: '2022-04-07',
                        line: '',
                        area: '',
                    },
                    {
                        type: '博时民泽纯债债券',
                        value: 0.0273,
                        date: '2022-04-20',
                        line: '',
                        area: '',
                    },
                    {
                        type: '博时民泽纯债债券',
                        value: 0.0282,
                        date: '2022-05-05',
                        line: '',
                        area: '',
                    },
                    {
                        type: '博时民泽纯债债券',
                        value: 0.029,
                        date: '2022-05-17',
                        line: '',
                        area: '',
                    },
                    {
                        type: '博时民泽纯债债券',
                        value: 0.0299,
                        date: '2022-05-30',
                        line: '',
                        area: '',
                    },
                    {
                        type: '博时民泽纯债债券',
                        value: 0.0305,
                        date: '2022-06-10',
                        line: '',
                        area: '',
                    },
                    {
                        type: '博时民泽纯债债券',
                        value: 0.0319,
                        date: '2022-06-23',
                        line: '',
                        area: '',
                    },
                    {
                        type: '博时民泽纯债债券',
                        value: 0.0313,
                        date: '2022-07-04',
                        line: '',
                        area: '',
                    },
                    {
                        type: '博时民泽纯债债券',
                        value: 0.0328,
                        date: '2022-07-13',
                        line: '',
                        area: '',
                    },
                    {
                        type: '博时民泽纯债债券',
                        value: 0.0357,
                        date: '2022-07-25',
                        line: '',
                        area: '',
                    },
                    {
                        type: '博时民泽纯债债券',
                        value: 0.0402,
                        date: '2022-08-03',
                        line: '',
                        area: '',
                    },
                    {
                        type: '博时民泽纯债债券',
                        value: 0.0387,
                        date: '2022-08-12',
                        line: '',
                        area: '',
                    },
                    {
                        type: '博时民泽纯债债券',
                        value: 0.041,
                        date: '2022-08-25',
                        line: '',
                        area: '',
                    },
                    {
                        type: '博时民泽纯债债券',
                        value: 0.0448,
                        date: '2022-09-06',
                        line: '',
                        area: '',
                    },
                    {
                        type: '博时民泽纯债债券',
                        value: 0.045,
                        date: '2022-09-21',
                        line: '',
                        area: '',
                    },
                ],
                style_type: 1,
                url: {
                    path: 'FundDetail',
                    type: 1,
                    params: {
                        code: '004136',
                    },
                },
            },
            {
                ui_style: 'default',
                id: 59,
                product_id: '000037',
                name: '广发景宁债券A',
                tags: ['低风险'],
                profit: '<span style="color:#E74949">5.38%</span>',
                profit_desc: '近一年收益率',
                reason_icon: 'https://static.licaimofang.com/wp-content/uploads/2022/09/gray_yh@3x.png',
                chart: [
                    {
                        type: '广发景宁债券A',
                        value: 0,
                        date: '2021-09-30',
                        line: '',
                        area: '',
                    },
                    {
                        type: '广发景宁债券A',
                        value: -0.0018,
                        date: '2021-10-20',
                        line: '',
                        area: '',
                    },
                    {
                        type: '广发景宁债券A',
                        value: 0.003,
                        date: '2021-10-29',
                        line: '',
                        area: '',
                    },
                    {
                        type: '广发景宁债券A',
                        value: 0.0073,
                        date: '2021-11-09',
                        line: '',
                        area: '',
                    },
                    {
                        type: '广发景宁债券A',
                        value: 0.0091,
                        date: '2021-11-19',
                        line: '',
                        area: '',
                    },
                    {
                        type: '广发景宁债券A',
                        value: 0.0122,
                        date: '2021-12-01',
                        line: '',
                        area: '',
                    },
                    {
                        type: '广发景宁债券A',
                        value: 0.0143,
                        date: '2021-12-10',
                        line: '',
                        area: '',
                    },
                    {
                        type: '广发景宁债券A',
                        value: 0.0153,
                        date: '2021-12-21',
                        line: '',
                        area: '',
                    },
                    {
                        type: '广发景宁债券A',
                        value: 0.0181,
                        date: '2021-12-30',
                        line: '',
                        area: '',
                    },
                    {
                        type: '广发景宁债券A',
                        value: 0.0203,
                        date: '2022-01-12',
                        line: '',
                        area: '',
                    },
                    {
                        type: '广发景宁债券A',
                        value: 0.0244,
                        date: '2022-01-21',
                        line: '',
                        area: '',
                    },
                    {
                        type: '广发景宁债券A',
                        value: 0.0266,
                        date: '2022-02-08',
                        line: '',
                        area: '',
                    },
                    {
                        type: '广发景宁债券A',
                        value: 0.0249,
                        date: '2022-02-18',
                        line: '',
                        area: '',
                    },
                    {
                        type: '广发景宁债券A',
                        value: 0.0224,
                        date: '2022-03-03',
                        line: '',
                        area: '',
                    },
                    {
                        type: '广发景宁债券A',
                        value: 0.0214,
                        date: '2022-03-14',
                        line: '',
                        area: '',
                    },
                    {
                        type: '广发景宁债券A',
                        value: 0.0209,
                        date: '2022-03-25',
                        line: '',
                        area: '',
                    },
                    {
                        type: '广发景宁债券A',
                        value: 0.0253,
                        date: '2022-04-07',
                        line: '',
                        area: '',
                    },
                    {
                        type: '广发景宁债券A',
                        value: 0.0285,
                        date: '2022-04-18',
                        line: '',
                        area: '',
                    },
                    {
                        type: '广发景宁债券A',
                        value: 0.0305,
                        date: '2022-04-27',
                        line: '',
                        area: '',
                    },
                    {
                        type: '广发景宁债券A',
                        value: 0.0333,
                        date: '2022-05-11',
                        line: '',
                        area: '',
                    },
                    {
                        type: '广发景宁债券A',
                        value: 0.0375,
                        date: '2022-05-20',
                        line: '',
                        area: '',
                    },
                    {
                        type: '广发景宁债券A',
                        value: 0.0384,
                        date: '2022-05-31',
                        line: '',
                        area: '',
                    },
                    {
                        type: '广发景宁债券A',
                        value: 0.0365,
                        date: '2022-06-10',
                        line: '',
                        area: '',
                    },
                    {
                        type: '广发景宁债券A',
                        value: 0.0383,
                        date: '2022-06-22',
                        line: '',
                        area: '',
                    },
                    {
                        type: '广发景宁债券A',
                        value: 0.0393,
                        date: '2022-07-01',
                        line: '',
                        area: '',
                    },
                    {
                        type: '广发景宁债券A',
                        value: 0.0414,
                        date: '2022-07-12',
                        line: '',
                        area: '',
                    },
                    {
                        type: '广发景宁债券A',
                        value: 0.0458,
                        date: '2022-07-21',
                        line: '',
                        area: '',
                    },
                    {
                        type: '广发景宁债券A',
                        value: 0.0494,
                        date: '2022-08-01',
                        line: '',
                        area: '',
                    },
                    {
                        type: '广发景宁债券A',
                        value: 0.0511,
                        date: '2022-08-10',
                        line: '',
                        area: '',
                    },
                    {
                        type: '广发景宁债券A',
                        value: 0.0533,
                        date: '2022-08-19',
                        line: '',
                        area: '',
                    },
                    {
                        type: '广发景宁债券A',
                        value: 0.0522,
                        date: '2022-08-30',
                        line: '',
                        area: '',
                    },
                    {
                        type: '广发景宁债券A',
                        value: 0.0546,
                        date: '2022-09-08',
                        line: '',
                        area: '',
                    },
                    {
                        type: '广发景宁债券A',
                        value: 0.0554,
                        date: '2022-09-21',
                        line: '',
                        area: '',
                    },
                ],
                style_type: 1,
                url: {
                    path: 'FundDetail',
                    type: 1,
                    params: {
                        code: '000037',
                    },
                },
            },
        ],
        style_type: 'default',
        recommend_score: 'score11111',
        plateid: 'convention',
        rec_json: '{"subject_id":101,"score":"score11111"}',
    },
    {
        subject_id: 102,
        header: {
            title: '固收+攻守兼备',
            title_desc: '',
            desc:
                '固收+属于稳健理财中稳重求进的投资策略。主投为风险水平较低的债券，适当配置部分股票；适合愿意长期持有，承受一定波动，追求较高收益的用户；',
            desc_icon: 'https://static.licaimofang.com/wp-content/uploads/2022/09/yh@3x.png',
            icon: '',
            bg_img: 'https://static.licaimofang.com/wp-content/uploads/2022/09/51664352728_.pic_.png',
            bg_linear: true,
            url: {
                path: 'SpecialDetail',
                type: 1,
                params: {
                    link: 'http://koudai-evolution-h5.yitao.mofanglicai.com.cn/specialDetail',
                    params: {
                        subject_id: 102,
                    },
                },
            },
        },
        img: '',
        img_url: '',
        items: [
            {
                ui_style: 'default',
                id: 60,
                product_id: '400020',
                name: '东方成长回报',
                tags: ['中高风险', '顺周期', '养老产业'],
                profit: '<span style="color:#4BA471">-19.19%</span>',
                profit_desc: '近一年收益率',
                reason_icon: 'https://static.licaimofang.com/wp-content/uploads/2022/09/gray_yh@3x.png',
                chart: [
                    {
                        type: '东方成长回报',
                        value: 0,
                        date: '2021-09-30',
                        line: '',
                        area: '',
                    },
                    {
                        type: '东方成长回报',
                        value: -0.006,
                        date: '2021-10-18',
                        line: '',
                        area: '',
                    },
                    {
                        type: '东方成长回报',
                        value: -0.0039,
                        date: '2021-10-27',
                        line: '',
                        area: '',
                    },
                    {
                        type: '东方成长回报',
                        value: -0.0166,
                        date: '2021-11-05',
                        line: '',
                        area: '',
                    },
                    {
                        type: '东方成长回报',
                        value: -0.0094,
                        date: '2021-11-16',
                        line: '',
                        area: '',
                    },
                    {
                        type: '东方成长回报',
                        value: 0.0148,
                        date: '2021-11-25',
                        line: '',
                        area: '',
                    },
                    {
                        type: '东方成长回报',
                        value: 0.0085,
                        date: '2021-12-06',
                        line: '',
                        area: '',
                    },
                    {
                        type: '东方成长回报',
                        value: 0.0132,
                        date: '2021-12-15',
                        line: '',
                        area: '',
                    },
                    {
                        type: '东方成长回报',
                        value: 0.0028,
                        date: '2021-12-24',
                        line: '',
                        area: '',
                    },
                    {
                        type: '东方成长回报',
                        value: -0.0172,
                        date: '2022-01-05',
                        line: '',
                        area: '',
                    },
                    {
                        type: '东方成长回报',
                        value: -0.025,
                        date: '2022-01-14',
                        line: '',
                        area: '',
                    },
                    {
                        type: '东方成长回报',
                        value: -0.0389,
                        date: '2022-01-25',
                        line: '',
                        area: '',
                    },
                    {
                        type: '东方成长回报',
                        value: -0.0539,
                        date: '2022-02-10',
                        line: '',
                        area: '',
                    },
                    {
                        type: '东方成长回报',
                        value: -0.0464,
                        date: '2022-02-21',
                        line: '',
                        area: '',
                    },
                    {
                        type: '东方成长回报',
                        value: -0.0458,
                        date: '2022-03-02',
                        line: '',
                        area: '',
                    },
                    {
                        type: '东方成长回报',
                        value: -0.0742,
                        date: '2022-03-11',
                        line: '',
                        area: '',
                    },
                    {
                        type: '东方成长回报',
                        value: -0.0892,
                        date: '2022-03-22',
                        line: '',
                        area: '',
                    },
                    {
                        type: '东方成长回报',
                        value: -0.0918,
                        date: '2022-03-31',
                        line: '',
                        area: '',
                    },
                    {
                        type: '东方成长回报',
                        value: -0.1082,
                        date: '2022-04-13',
                        line: '',
                        area: '',
                    },
                    {
                        type: '东方成长回报',
                        value: -0.1196,
                        date: '2022-04-22',
                        line: '',
                        area: '',
                    },
                    {
                        type: '东方成长回报',
                        value: -0.1367,
                        date: '2022-05-06',
                        line: '',
                        area: '',
                    },
                    {
                        type: '东方成长回报',
                        value: -0.1306,
                        date: '2022-05-17',
                        line: '',
                        area: '',
                    },
                    {
                        type: '东方成长回报',
                        value: -0.13,
                        date: '2022-05-26',
                        line: '',
                        area: '',
                    },
                    {
                        type: '东方成长回报',
                        value: -0.13,
                        date: '2022-06-07',
                        line: '',
                        area: '',
                    },
                    {
                        type: '东方成长回报',
                        value: -0.1295,
                        date: '2022-06-16',
                        line: '',
                        area: '',
                    },
                    {
                        type: '东方成长回报',
                        value: -0.1262,
                        date: '2022-06-27',
                        line: '',
                        area: '',
                    },
                    {
                        type: '东方成长回报',
                        value: -0.1276,
                        date: '2022-07-06',
                        line: '',
                        area: '',
                    },
                    {
                        type: '东方成长回报',
                        value: -0.142,
                        date: '2022-07-15',
                        line: '',
                        area: '',
                    },
                    {
                        type: '东方成长回报',
                        value: -0.1438,
                        date: '2022-07-26',
                        line: '',
                        area: '',
                    },
                    {
                        type: '东方成长回报',
                        value: -0.1441,
                        date: '2022-08-04',
                        line: '',
                        area: '',
                    },
                    {
                        type: '东方成长回报',
                        value: -0.1463,
                        date: '2022-08-15',
                        line: '',
                        area: '',
                    },
                    {
                        type: '东方成长回报',
                        value: -0.1489,
                        date: '2022-08-24',
                        line: '',
                        area: '',
                    },
                    {
                        type: '东方成长回报',
                        value: -0.1583,
                        date: '2022-09-02',
                        line: '',
                        area: '',
                    },
                    {
                        type: '东方成长回报',
                        value: -0.1577,
                        date: '2022-09-14',
                        line: '',
                        area: '',
                    },
                    {
                        type: '东方成长回报',
                        value: -0.185,
                        date: '2022-09-23',
                        line: '',
                        area: '',
                    },
                ],
                style_type: 1,
                url: {
                    path: 'FundDetail',
                    type: 1,
                    params: {
                        code: '400020',
                    },
                },
            },
            {
                ui_style: 'default',
                id: 61,
                product_id: '001247',
                name: '华泰柏瑞新利A',
                tags: ['中风险', '黄金珠宝', '融资融券标的'],
                profit: '<span style="color:#E74949">6.99%</span>',
                profit_desc: '近一年收益率',
                reason_icon: 'https://static.licaimofang.com/wp-content/uploads/2022/09/gray_yh@3x.png',
                chart: [
                    {
                        type: '华泰柏瑞新利A',
                        value: 0,
                        date: '2021-09-30',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞新利A',
                        value: 0.0021,
                        date: '2021-10-18',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞新利A',
                        value: 0.0005,
                        date: '2021-10-27',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞新利A',
                        value: 0.0001,
                        date: '2021-11-05',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞新利A',
                        value: 0.0068,
                        date: '2021-11-16',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞新利A',
                        value: 0.0144,
                        date: '2021-11-25',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞新利A',
                        value: 0.0164,
                        date: '2021-12-06',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞新利A',
                        value: 0.0177,
                        date: '2021-12-15',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞新利A',
                        value: 0.0191,
                        date: '2021-12-24',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞新利A',
                        value: 0.0232,
                        date: '2022-01-05',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞新利A',
                        value: 0.0239,
                        date: '2022-01-14',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞新利A',
                        value: 0.0254,
                        date: '2022-01-25',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞新利A',
                        value: 0.0325,
                        date: '2022-02-10',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞新利A',
                        value: 0.0338,
                        date: '2022-02-21',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞新利A',
                        value: 0.035,
                        date: '2022-03-02',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞新利A',
                        value: 0.0261,
                        date: '2022-03-11',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞新利A',
                        value: 0.022,
                        date: '2022-03-22',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞新利A',
                        value: 0.0244,
                        date: '2022-03-31',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞新利A',
                        value: 0.0315,
                        date: '2022-04-13',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞新利A',
                        value: 0.0214,
                        date: '2022-04-22',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞新利A',
                        value: 0.0173,
                        date: '2022-05-06',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞新利A',
                        value: 0.0291,
                        date: '2022-05-17',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞新利A',
                        value: 0.0345,
                        date: '2022-05-26',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞新利A',
                        value: 0.0435,
                        date: '2022-06-07',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞新利A',
                        value: 0.0471,
                        date: '2022-06-16',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞新利A',
                        value: 0.0511,
                        date: '2022-06-27',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞新利A',
                        value: 0.0473,
                        date: '2022-07-06',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞新利A',
                        value: 0.0473,
                        date: '2022-07-15',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞新利A',
                        value: 0.0602,
                        date: '2022-07-26',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞新利A',
                        value: 0.0592,
                        date: '2022-08-04',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞新利A',
                        value: 0.069,
                        date: '2022-08-15',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞新利A',
                        value: 0.0676,
                        date: '2022-08-24',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞新利A',
                        value: 0.0692,
                        date: '2022-09-02',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞新利A',
                        value: 0.0786,
                        date: '2022-09-14',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞新利A',
                        value: 0.0754,
                        date: '2022-09-23',
                        line: '',
                        area: '',
                    },
                ],
                style_type: 1,
                url: {
                    path: 'FundDetail',
                    type: 1,
                    params: {
                        code: '001247',
                    },
                },
            },
            {
                ui_style: 'default',
                id: 62,
                product_id: '004010',
                name: '华泰柏瑞鼎利A',
                tags: ['中低风险', '黄金珠宝', '融资融券标的'],
                profit: '<span style="color:#E74949">7.09%</span>',
                profit_desc: '近一年收益率',
                reason_icon: 'https://static.licaimofang.com/wp-content/uploads/2022/09/gray_yh@3x.png',
                chart: [
                    {
                        type: '华泰柏瑞鼎利A',
                        value: 0,
                        date: '2021-09-30',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞鼎利A',
                        value: 0.0031,
                        date: '2021-10-18',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞鼎利A',
                        value: 0.0015,
                        date: '2021-10-27',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞鼎利A',
                        value: 0.001,
                        date: '2021-11-05',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞鼎利A',
                        value: 0.0075,
                        date: '2021-11-16',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞鼎利A',
                        value: 0.016,
                        date: '2021-11-25',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞鼎利A',
                        value: 0.0182,
                        date: '2021-12-06',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞鼎利A',
                        value: 0.0196,
                        date: '2021-12-15',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞鼎利A',
                        value: 0.0209,
                        date: '2021-12-24',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞鼎利A',
                        value: 0.0249,
                        date: '2022-01-05',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞鼎利A',
                        value: 0.0252,
                        date: '2022-01-14',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞鼎利A',
                        value: 0.0267,
                        date: '2022-01-25',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞鼎利A',
                        value: 0.0341,
                        date: '2022-02-10',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞鼎利A',
                        value: 0.0354,
                        date: '2022-02-21',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞鼎利A',
                        value: 0.0362,
                        date: '2022-03-02',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞鼎利A',
                        value: 0.0272,
                        date: '2022-03-11',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞鼎利A',
                        value: 0.0226,
                        date: '2022-03-22',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞鼎利A',
                        value: 0.025,
                        date: '2022-03-31',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞鼎利A',
                        value: 0.0317,
                        date: '2022-04-13',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞鼎利A',
                        value: 0.0221,
                        date: '2022-04-22',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞鼎利A',
                        value: 0.0188,
                        date: '2022-05-06',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞鼎利A',
                        value: 0.03,
                        date: '2022-05-17',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞鼎利A',
                        value: 0.0351,
                        date: '2022-05-26',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞鼎利A',
                        value: 0.0436,
                        date: '2022-06-07',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞鼎利A',
                        value: 0.0472,
                        date: '2022-06-16',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞鼎利A',
                        value: 0.051,
                        date: '2022-06-27',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞鼎利A',
                        value: 0.0475,
                        date: '2022-07-06',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞鼎利A',
                        value: 0.0472,
                        date: '2022-07-15',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞鼎利A',
                        value: 0.06,
                        date: '2022-07-26',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞鼎利A',
                        value: 0.0592,
                        date: '2022-08-04',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞鼎利A',
                        value: 0.0695,
                        date: '2022-08-15',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞鼎利A',
                        value: 0.0682,
                        date: '2022-08-24',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞鼎利A',
                        value: 0.07,
                        date: '2022-09-02',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞鼎利A',
                        value: 0.0792,
                        date: '2022-09-14',
                        line: '',
                        area: '',
                    },
                    {
                        type: '华泰柏瑞鼎利A',
                        value: 0.0761,
                        date: '2022-09-23',
                        line: '',
                        area: '',
                    },
                ],
                style_type: 1,
                url: {
                    path: 'FundDetail',
                    type: 1,
                    params: {
                        code: '004010',
                    },
                },
            },
        ],
        style_type: 'default',
        recommend_score: 'score11111',
        plateid: 'convention',
        rec_json: '{"subject_id":102,"score":"score11111"}',
    },
    {
        subject_id: 103,
        header: {
            title: '爆款股基',
            title_desc: '',
            desc:
                '优选股基主要精选的是中风险以上的股票型基金。适合想要追求更高收益，且能够承受一定风险和波动的投资者。本专题精选近1年收益率排名前25%，且最大回撤较低的优质股基。规模均超过10亿，时间均超过四年。',
            desc_icon: 'https://static.licaimofang.com/wp-content/uploads/2022/09/yh@3x.png',
            icon: '',
            bg_img: 'https://static.licaimofang.com/wp-content/uploads/2022/09/51664352728_.pic_.png',
            bg_linear: true,
            url: {
                path: 'SpecialDetail',
                type: 1,
                params: {
                    link: 'http://koudai-evolution-h5.yitao.mofanglicai.com.cn/specialDetail',
                    params: {
                        subject_id: 103,
                    },
                },
            },
        },
        img: '',
        img_url: '',
        items: [
            {
                ui_style: 'default',
                id: 115,
                product_id: '002910',
                name: '易方达供给改革',
                tags: ['中风险', '顺周期', '债转股'],
                profit: '<span style="color:#E74949">24.77%</span>',
                profit_desc: '近一年收益率',
                reason_icon: 'https://static.licaimofang.com/wp-content/uploads/2022/09/gray_yh@3x.png',
                chart: [
                    {
                        type: '易方达供给改革',
                        value: 0,
                        date: '2021-09-30',
                        line: '',
                        area: '',
                    },
                    {
                        type: '易方达供给改革',
                        value: 0.0096,
                        date: '2021-10-18',
                        line: '',
                        area: '',
                    },
                    {
                        type: '易方达供给改革',
                        value: -0.013,
                        date: '2021-10-27',
                        line: '',
                        area: '',
                    },
                    {
                        type: '易方达供给改革',
                        value: -0.0621,
                        date: '2021-11-05',
                        line: '',
                        area: '',
                    },
                    {
                        type: '易方达供给改革',
                        value: -0.0238,
                        date: '2021-11-16',
                        line: '',
                        area: '',
                    },
                    {
                        type: '易方达供给改革',
                        value: 0.0365,
                        date: '2021-11-25',
                        line: '',
                        area: '',
                    },
                    {
                        type: '易方达供给改革',
                        value: 0.0468,
                        date: '2021-12-06',
                        line: '',
                        area: '',
                    },
                    {
                        type: '易方达供给改革',
                        value: 0.0349,
                        date: '2021-12-15',
                        line: '',
                        area: '',
                    },
                    {
                        type: '易方达供给改革',
                        value: 0.0519,
                        date: '2021-12-24',
                        line: '',
                        area: '',
                    },
                    {
                        type: '易方达供给改革',
                        value: 0.0506,
                        date: '2022-01-05',
                        line: '',
                        area: '',
                    },
                    {
                        type: '易方达供给改革',
                        value: 0.064,
                        date: '2022-01-14',
                        line: '',
                        area: '',
                    },
                    {
                        type: '易方达供给改革',
                        value: 0.0224,
                        date: '2022-01-25',
                        line: '',
                        area: '',
                    },
                    {
                        type: '易方达供给改革',
                        value: 0.0575,
                        date: '2022-02-10',
                        line: '',
                        area: '',
                    },
                    {
                        type: '易方达供给改革',
                        value: 0.0614,
                        date: '2022-02-21',
                        line: '',
                        area: '',
                    },
                    {
                        type: '易方达供给改革',
                        value: 0.0904,
                        date: '2022-03-02',
                        line: '',
                        area: '',
                    },
                    {
                        type: '易方达供给改革',
                        value: 0.0356,
                        date: '2022-03-11',
                        line: '',
                        area: '',
                    },
                    {
                        type: '易方达供给改革',
                        value: 0.0321,
                        date: '2022-03-22',
                        line: '',
                        area: '',
                    },
                    {
                        type: '易方达供给改革',
                        value: 0.0232,
                        date: '2022-03-31',
                        line: '',
                        area: '',
                    },
                    {
                        type: '易方达供给改革',
                        value: -0.0293,
                        date: '2022-04-13',
                        line: '',
                        area: '',
                    },
                    {
                        type: '易方达供给改革',
                        value: -0.0801,
                        date: '2022-04-22',
                        line: '',
                        area: '',
                    },
                    {
                        type: '易方达供给改革',
                        value: -0.0623,
                        date: '2022-05-06',
                        line: '',
                        area: '',
                    },
                    {
                        type: '易方达供给改革',
                        value: -0.0017,
                        date: '2022-05-17',
                        line: '',
                        area: '',
                    },
                    {
                        type: '易方达供给改革',
                        value: 0.0468,
                        date: '2022-05-26',
                        line: '',
                        area: '',
                    },
                    {
                        type: '易方达供给改革',
                        value: 0.125,
                        date: '2022-06-07',
                        line: '',
                        area: '',
                    },
                    {
                        type: '易方达供给改革',
                        value: 0.1547,
                        date: '2022-06-16',
                        line: '',
                        area: '',
                    },
                    {
                        type: '易方达供给改革',
                        value: 0.1973,
                        date: '2022-06-27',
                        line: '',
                        area: '',
                    },
                    {
                        type: '易方达供给改革',
                        value: 0.176,
                        date: '2022-07-06',
                        line: '',
                        area: '',
                    },
                    {
                        type: '易方达供给改革',
                        value: 0.1944,
                        date: '2022-07-15',
                        line: '',
                        area: '',
                    },
                    {
                        type: '易方达供给改革',
                        value: 0.2473,
                        date: '2022-07-26',
                        line: '',
                        area: '',
                    },
                    {
                        type: '易方达供给改革',
                        value: 0.2564,
                        date: '2022-08-04',
                        line: '',
                        area: '',
                    },
                    {
                        type: '易方达供给改革',
                        value: 0.3552,
                        date: '2022-08-15',
                        line: '',
                        area: '',
                    },
                    {
                        type: '易方达供给改革',
                        value: 0.3582,
                        date: '2022-08-24',
                        line: '',
                        area: '',
                    },
                    {
                        type: '易方达供给改革',
                        value: 0.3131,
                        date: '2022-09-02',
                        line: '',
                        area: '',
                    },
                    {
                        type: '易方达供给改革',
                        value: 0.3479,
                        date: '2022-09-14',
                        line: '',
                        area: '',
                    },
                    {
                        type: '易方达供给改革',
                        value: 0.296,
                        date: '2022-09-23',
                        line: '',
                        area: '',
                    },
                ],
                style_type: 1,
                url: {
                    path: 'FundDetail',
                    type: 1,
                    params: {
                        code: '002910',
                    },
                },
            },
            {
                ui_style: 'default',
                id: 116,
                product_id: '001156',
                name: '申万菱信新能源汽车',
                tags: ['中风险', '顺周期', '碳中和'],
                profit: '<span style="color:#4BA471">-9.40%</span>',
                profit_desc: '近一年收益率',
                reason_icon: 'https://static.licaimofang.com/wp-content/uploads/2022/09/gray_yh@3x.png',
                chart: [
                    {
                        type: '申万菱信新能源汽车',
                        value: 0,
                        date: '2021-09-30',
                        line: '',
                        area: '',
                    },
                    {
                        type: '申万菱信新能源汽车',
                        value: 0.037,
                        date: '2021-10-18',
                        line: '',
                        area: '',
                    },
                    {
                        type: '申万菱信新能源汽车',
                        value: 0.1156,
                        date: '2021-10-27',
                        line: '',
                        area: '',
                    },
                    {
                        type: '申万菱信新能源汽车',
                        value: 0.0542,
                        date: '2021-11-05',
                        line: '',
                        area: '',
                    },
                    {
                        type: '申万菱信新能源汽车',
                        value: 0.0309,
                        date: '2021-11-16',
                        line: '',
                        area: '',
                    },
                    {
                        type: '申万菱信新能源汽车',
                        value: 0.0711,
                        date: '2021-11-25',
                        line: '',
                        area: '',
                    },
                    {
                        type: '申万菱信新能源汽车',
                        value: 0.07,
                        date: '2021-12-06',
                        line: '',
                        area: '',
                    },
                    {
                        type: '申万菱信新能源汽车',
                        value: 0.0671,
                        date: '2021-12-15',
                        line: '',
                        area: '',
                    },
                    {
                        type: '申万菱信新能源汽车',
                        value: -0.0316,
                        date: '2021-12-24',
                        line: '',
                        area: '',
                    },
                    {
                        type: '申万菱信新能源汽车',
                        value: -0.056,
                        date: '2022-01-05',
                        line: '',
                        area: '',
                    },
                    {
                        type: '申万菱信新能源汽车',
                        value: -0.0413,
                        date: '2022-01-14',
                        line: '',
                        area: '',
                    },
                    {
                        type: '申万菱信新能源汽车',
                        value: -0.075,
                        date: '2022-01-25',
                        line: '',
                        area: '',
                    },
                    {
                        type: '申万菱信新能源汽车',
                        value: -0.1429,
                        date: '2022-02-10',
                        line: '',
                        area: '',
                    },
                    {
                        type: '申万菱信新能源汽车',
                        value: -0.1019,
                        date: '2022-02-21',
                        line: '',
                        area: '',
                    },
                    {
                        type: '申万菱信新能源汽车',
                        value: -0.0531,
                        date: '2022-03-02',
                        line: '',
                        area: '',
                    },
                    {
                        type: '申万菱信新能源汽车',
                        value: -0.0962,
                        date: '2022-03-11',
                        line: '',
                        area: '',
                    },
                    {
                        type: '申万菱信新能源汽车',
                        value: -0.0797,
                        date: '2022-03-22',
                        line: '',
                        area: '',
                    },
                    {
                        type: '申万菱信新能源汽车',
                        value: -0.1163,
                        date: '2022-03-31',
                        line: '',
                        area: '',
                    },
                    {
                        type: '申万菱信新能源汽车',
                        value: -0.1744,
                        date: '2022-04-13',
                        line: '',
                        area: '',
                    },
                    {
                        type: '申万菱信新能源汽车',
                        value: -0.2268,
                        date: '2022-04-22',
                        line: '',
                        area: '',
                    },
                    {
                        type: '申万菱信新能源汽车',
                        value: -0.2125,
                        date: '2022-05-06',
                        line: '',
                        area: '',
                    },
                    {
                        type: '申万菱信新能源汽车',
                        value: -0.145,
                        date: '2022-05-17',
                        line: '',
                        area: '',
                    },
                    {
                        type: '申万菱信新能源汽车',
                        value: -0.1231,
                        date: '2022-05-26',
                        line: '',
                        area: '',
                    },
                    {
                        type: '申万菱信新能源汽车',
                        value: -0.0309,
                        date: '2022-06-07',
                        line: '',
                        area: '',
                    },
                    {
                        type: '申万菱信新能源汽车',
                        value: -0.0029,
                        date: '2022-06-16',
                        line: '',
                        area: '',
                    },
                    {
                        type: '申万菱信新能源汽车',
                        value: 0.098,
                        date: '2022-06-27',
                        line: '',
                        area: '',
                    },
                    {
                        type: '申万菱信新能源汽车',
                        value: 0.103,
                        date: '2022-07-06',
                        line: '',
                        area: '',
                    },
                    {
                        type: '申万菱信新能源汽车',
                        value: 0.0991,
                        date: '2022-07-15',
                        line: '',
                        area: '',
                    },
                    {
                        type: '申万菱信新能源汽车',
                        value: 0.0716,
                        date: '2022-07-26',
                        line: '',
                        area: '',
                    },
                    {
                        type: '申万菱信新能源汽车',
                        value: 0.0555,
                        date: '2022-08-04',
                        line: '',
                        area: '',
                    },
                    {
                        type: '申万菱信新能源汽车',
                        value: 0.0864,
                        date: '2022-08-15',
                        line: '',
                        area: '',
                    },
                    {
                        type: '申万菱信新能源汽车',
                        value: 0.0526,
                        date: '2022-08-24',
                        line: '',
                        area: '',
                    },
                    {
                        type: '申万菱信新能源汽车',
                        value: -0.0139,
                        date: '2022-09-02',
                        line: '',
                        area: '',
                    },
                    {
                        type: '申万菱信新能源汽车',
                        value: -0.0085,
                        date: '2022-09-14',
                        line: '',
                        area: '',
                    },
                    {
                        type: '申万菱信新能源汽车',
                        value: -0.0568,
                        date: '2022-09-23',
                        line: '',
                        area: '',
                    },
                ],
                style_type: 1,
                url: {
                    path: 'FundDetail',
                    type: 1,
                    params: {
                        code: '001156',
                    },
                },
            },
            {
                ui_style: 'default',
                id: 117,
                product_id: '000729',
                name: '建信中小盘A',
                tags: ['中风险', '顺周期', '碳中和'],
                profit: '<span style="color:#E74949">11.90%</span>',
                profit_desc: '近一年收益率',
                reason_icon: 'https://static.licaimofang.com/wp-content/uploads/2022/09/gray_yh@3x.png',
                chart: [
                    {
                        type: '建信中小盘A',
                        value: 0,
                        date: '2021-09-30',
                        line: '',
                        area: '',
                    },
                    {
                        type: '建信中小盘A',
                        value: -0.0019,
                        date: '2021-10-18',
                        line: '',
                        area: '',
                    },
                    {
                        type: '建信中小盘A',
                        value: 0.0554,
                        date: '2021-10-27',
                        line: '',
                        area: '',
                    },
                    {
                        type: '建信中小盘A',
                        value: 0.0746,
                        date: '2021-11-05',
                        line: '',
                        area: '',
                    },
                    {
                        type: '建信中小盘A',
                        value: 0.0669,
                        date: '2021-11-16',
                        line: '',
                        area: '',
                    },
                    {
                        type: '建信中小盘A',
                        value: 0.1105,
                        date: '2021-11-25',
                        line: '',
                        area: '',
                    },
                    {
                        type: '建信中小盘A',
                        value: 0.1179,
                        date: '2021-12-06',
                        line: '',
                        area: '',
                    },
                    {
                        type: '建信中小盘A',
                        value: 0.1297,
                        date: '2021-12-15',
                        line: '',
                        area: '',
                    },
                    {
                        type: '建信中小盘A',
                        value: 0.0971,
                        date: '2021-12-24',
                        line: '',
                        area: '',
                    },
                    {
                        type: '建信中小盘A',
                        value: 0.0701,
                        date: '2022-01-05',
                        line: '',
                        area: '',
                    },
                    {
                        type: '建信中小盘A',
                        value: 0.0163,
                        date: '2022-01-14',
                        line: '',
                        area: '',
                    },
                    {
                        type: '建信中小盘A',
                        value: -0.0222,
                        date: '2022-01-25',
                        line: '',
                        area: '',
                    },
                    {
                        type: '建信中小盘A',
                        value: -0.0016,
                        date: '2022-02-10',
                        line: '',
                        area: '',
                    },
                    {
                        type: '建信中小盘A',
                        value: 0.0297,
                        date: '2022-02-21',
                        line: '',
                        area: '',
                    },
                    {
                        type: '建信中小盘A',
                        value: 0.0768,
                        date: '2022-03-02',
                        line: '',
                        area: '',
                    },
                    {
                        type: '建信中小盘A',
                        value: 0.0206,
                        date: '2022-03-11',
                        line: '',
                        area: '',
                    },
                    {
                        type: '建信中小盘A',
                        value: 0.0225,
                        date: '2022-03-22',
                        line: '',
                        area: '',
                    },
                    {
                        type: '建信中小盘A',
                        value: 0.0131,
                        date: '2022-03-31',
                        line: '',
                        area: '',
                    },
                    {
                        type: '建信中小盘A',
                        value: -0.0511,
                        date: '2022-04-13',
                        line: '',
                        area: '',
                    },
                    {
                        type: '建信中小盘A',
                        value: -0.1019,
                        date: '2022-04-22',
                        line: '',
                        area: '',
                    },
                    {
                        type: '建信中小盘A',
                        value: -0.1137,
                        date: '2022-05-06',
                        line: '',
                        area: '',
                    },
                    {
                        type: '建信中小盘A',
                        value: -0.0554,
                        date: '2022-05-17',
                        line: '',
                        area: '',
                    },
                    {
                        type: '建信中小盘A',
                        value: 0.0037,
                        date: '2022-05-26',
                        line: '',
                        area: '',
                    },
                    {
                        type: '建信中小盘A',
                        value: 0.0792,
                        date: '2022-06-07',
                        line: '',
                        area: '',
                    },
                    {
                        type: '建信中小盘A',
                        value: 0.0928,
                        date: '2022-06-16',
                        line: '',
                        area: '',
                    },
                    {
                        type: '建信中小盘A',
                        value: 0.1369,
                        date: '2022-06-27',
                        line: '',
                        area: '',
                    },
                    {
                        type: '建信中小盘A',
                        value: 0.1428,
                        date: '2022-07-06',
                        line: '',
                        area: '',
                    },
                    {
                        type: '建信中小盘A',
                        value: 0.1332,
                        date: '2022-07-15',
                        line: '',
                        area: '',
                    },
                    {
                        type: '建信中小盘A',
                        value: 0.1466,
                        date: '2022-07-26',
                        line: '',
                        area: '',
                    },
                    {
                        type: '建信中小盘A',
                        value: 0.145,
                        date: '2022-08-04',
                        line: '',
                        area: '',
                    },
                    {
                        type: '建信中小盘A',
                        value: 0.241,
                        date: '2022-08-15',
                        line: '',
                        area: '',
                    },
                    {
                        type: '建信中小盘A',
                        value: 0.2404,
                        date: '2022-08-24',
                        line: '',
                        area: '',
                    },
                    {
                        type: '建信中小盘A',
                        value: 0.1864,
                        date: '2022-09-02',
                        line: '',
                        area: '',
                    },
                    {
                        type: '建信中小盘A',
                        value: 0.2279,
                        date: '2022-09-14',
                        line: '',
                        area: '',
                    },
                    {
                        type: '建信中小盘A',
                        value: 0.1623,
                        date: '2022-09-23',
                        line: '',
                        area: '',
                    },
                ],
                style_type: 1,
                url: {
                    path: 'FundDetail',
                    type: 1,
                    params: {
                        code: '000729',
                    },
                },
            },
        ],
        style_type: 'default',
        recommend_score: 'score11111',
        plateid: 'convention',
        rec_json: '{"subject_id":103,"score":"score11111"}',
    },
];
